services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI} # Make sure this environment variable is set in your .env file
      SECRET: ${SECRET}
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_PROD_API_URL: ${REACT_APP_PROD_API_URL}
